from __future__ import annotations

from pathlib import Path
import json
import os
import shutil
import subprocess
import sys
import tempfile

from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware


app = FastAPI(title="Prototype V1 API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

BASE_DIR = Path(__file__).resolve().parent
WATCH_SCRIPT = BASE_DIR / "watch_latest_image.py"
LATEST_RESPONSE_JSON = BASE_DIR / "results" / "latest_response.json"

_ALLOWED_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp"}


@app.get("/latest")
async def latest():
    if not LATEST_RESPONSE_JSON.exists():
        raise HTTPException(
            status_code=404,
            detail="latest_response.json not found.",
        )

    try:
        return json.loads(LATEST_RESPONSE_JSON.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise HTTPException(
            status_code=500,
            detail=f"latest_response.json is not valid JSON: {exc}",
        ) from exc


@app.post("/analyze")
async def analyze(file: UploadFile = File(...)):
    suffix = Path(file.filename or "upload.bin").suffix.lower()
    if suffix not in _ALLOWED_EXTENSIONS:
        raise HTTPException(
            status_code=400,
            detail="Unsupported file type. Use .png, .jpg, .jpeg, or .webp.",
        )

    temp_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
            temp_path = Path(tmp.name)
            file.file.seek(0)
            shutil.copyfileobj(file.file, tmp)

        command = [sys.executable, str(WATCH_SCRIPT), str(temp_path)]
        result = subprocess.run(
            command,
            cwd=str(BASE_DIR),
            capture_output=True,
            text=True,
            check=False,
            env=os.environ.copy(),
        )

        if result.returncode != 0:
            stderr = (result.stderr or result.stdout or "").strip()
            raise HTTPException(
                status_code=500,
                detail=f"Image analysis pipeline failed: {stderr}",
            )

        if not LATEST_RESPONSE_JSON.exists():
            raise HTTPException(
                status_code=500,
                detail="latest_response.json was not generated by the pipeline.",
            )

        try:
            return json.loads(LATEST_RESPONSE_JSON.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise HTTPException(
                status_code=500,
                detail=f"latest_response.json is not valid JSON: {exc}",
            ) from exc
    finally:
        try:
            await file.close()
        finally:
            if temp_path and temp_path.exists():
                temp_path.unlink(missing_ok=True)
