from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Annotated, Literal, Union
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


PROJECT_CONVERSATION_SCHEMA_VERSION = "1.0"
CONVERSATION_TURN_SCHEMA_VERSION = "1.0"
MAX_CONVERSATION_TEXT_LENGTH = 8000
MAX_CONVERSATION_IMAGE_REFERENCES = 5


class ConversationRole(str, Enum):
    USER = "USER"
    ASSISTANT = "ASSISTANT"


class ConversationTurnStatus(str, Enum):
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ConversationTextPart(BaseModel):
    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    type: Literal["TEXT"] = "TEXT"
    text: str = Field(min_length=1, max_length=MAX_CONVERSATION_TEXT_LENGTH)


class ConversationEvidenceReferencePart(BaseModel):
    """Provider-neutral pointer to canonical Investigation Evidence; never contains bytes."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    type: Literal["PROJECT_RESOURCE_REFERENCE"] = "PROJECT_RESOURCE_REFERENCE"
    resource_kind: Literal["EVIDENCE"] = "EVIDENCE"
    resource_id: str
    relationship: Literal["ATTACHED"] = "ATTACHED"
    container_kind: Literal["INVESTIGATION_SESSION"] = "INVESTIGATION_SESSION"
    container_id: str

    @field_validator("resource_id", "container_id")
    @classmethod
    def _validate_uuid(cls, value: str) -> str:
        try:
            return str(UUID(str(value)))
        except ValueError as exc:
            raise ValueError("Evidence reference identity fields must be valid UUIDs.") from exc


class ConversationExploreReferencePart(BaseModel):
    """Phase 3A: provider-neutral pointer to a canonical Explore interaction (the existing
    ProjectExploreService's own idempotency-derived interaction_id) - never contains provider-native
    structures or a duplicated copy of the options/result. The interaction_id is the single source
    of truth, already fetchable via the existing Explore endpoints
    (GET /projects/{project_id}/ai-results/explore-plan/{interaction_id} or read_projection). Kept
    deliberately separate from ConversationEvidenceReferencePart rather than widening its Literals:
    an Explore interaction has no Investigation session container and is not "Evidence", and the
    existing assistant-turns-cannot-attach-Evidence invariant below must not need a resource_kind
    exception carved into it.
    """

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    type: Literal["EXPLORE_REFERENCE"] = "EXPLORE_REFERENCE"
    interaction_id: str

    @field_validator("interaction_id")
    @classmethod
    def _validate_uuid(cls, value: str) -> str:
        try:
            return str(UUID(str(value)))
        except ValueError as exc:
            raise ValueError("interaction_id must be a valid UUID.") from exc


class ConversationVisualArtifactReferencePart(BaseModel):
    """Phase 3B: provider-neutral pointer to a canonical VisualArtifact - never contains image bytes
    or a duplicated copy of the artifact's own status/provenance. The (project_ai_result_id,
    option_id, artifact_id) triple is exactly the existing VisualArtifact identity already used by
    the existing HTTP routes (GET .../ai-results/explore-plan/{result_id}/options/{option_id}/
    visual-artifacts/{artifact_id}) - the conversation introduces no second identity scheme and no
    second image store; VisualArtifactStore remains the sole owner of the generated bytes.
    """

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    type: Literal["VISUAL_ARTIFACT_REFERENCE"] = "VISUAL_ARTIFACT_REFERENCE"
    project_ai_result_id: str
    option_id: str
    artifact_id: str

    @field_validator("project_ai_result_id", "option_id", "artifact_id")
    @classmethod
    def _validate_uuid(cls, value: str) -> str:
        try:
            return str(UUID(str(value)))
        except ValueError as exc:
            raise ValueError("Visual artifact reference identity fields must be valid UUIDs.") from exc


class ConversationInvestigationReferencePart(BaseModel):
    """Phase 3C: provider-neutral pointer to a canonical, durable Investigation session/result -
    never contains the diagnosis/next-action bodies themselves (those live in the assistant turn's
    own TEXT part, generated fresh from the canonical result at bridge time) and never image bytes.
    Only ever attached for a session/evidence-backed (Path A) result; a text-only (Path B) result
    has no durable session to reference and stays plain TEXT, exactly like GENERAL_GUIDANCE's own
    ephemeral outputs. The session identity is the same one the existing Investigation HTTP routes
    and trust-decision endpoints already use - no second identity scheme.
    """

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    type: Literal["INVESTIGATION_REFERENCE"] = "INVESTIGATION_REFERENCE"
    investigation_session_id: str

    @field_validator("investigation_session_id")
    @classmethod
    def _validate_uuid(cls, value: str) -> str:
        try:
            return str(UUID(str(value)))
        except ValueError as exc:
            raise ValueError("investigation_session_id must be a valid UUID.") from exc


ConversationContentPart = Annotated[
    Union[
        ConversationTextPart, ConversationEvidenceReferencePart,
        ConversationExploreReferencePart, ConversationVisualArtifactReferencePart,
        ConversationInvestigationReferencePart,
    ],
    Field(discriminator="type"),
]


class ConversationProviderProvenance(BaseModel):
    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    provider: str = Field(min_length=1, max_length=64)
    model: str = Field(min_length=1, max_length=200)
    request_id: str | None = Field(default=None, max_length=200)
    # Stage 3 (Visual Evidence Continuity) inspectability: which retrieval tier (if any) this turn
    # used and which Evidence it selected - populated only when the deterministic+AI visual
    # continuity retrieval actually fired for this turn (see AssistantOrchestrator.send()). None for
    # every ordinary turn, including one with freshly-attached evidence_refs (that is not a
    # "retrieval" - the image was already given this turn, not looked up from history).
    visual_retrieval_tier: str | None = Field(default=None, max_length=32)
    visual_evidence_id: str | None = Field(default=None, max_length=64)
    # Stage 4 (Real Conversation Integration) inspectability: which Structured Project Memory
    # retrieval intent (if any) this turn used and which subject it resolved to - populated only
    # when memory-aware retrieval actually contributed context (see AssistantOrchestrator.send()).
    memory_retrieval_intent: str | None = Field(default=None, max_length=32)
    memory_retrieval_subject: str | None = Field(default=None, max_length=80)


class ConversationTurn(BaseModel):
    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    schema_version: str = CONVERSATION_TURN_SCHEMA_VERSION
    turn_id: str
    conversation_id: str
    project_id: str
    sequence_number: int = Field(ge=1)
    role: ConversationRole
    status: ConversationTurnStatus
    content_parts: list[ConversationContentPart] = Field(
        min_length=1, max_length=1 + MAX_CONVERSATION_IMAGE_REFERENCES)
    idempotency_key: str = Field(min_length=1, max_length=128)
    request_fingerprint: str = Field(min_length=64, max_length=64)
    created_at_utc: datetime
    completed_at_utc: datetime | None = None
    provider_provenance: ConversationProviderProvenance | None = None
    failure_category: str | None = Field(default=None, max_length=100)
    failure_message: str | None = Field(default=None, max_length=500)

    @field_validator("turn_id", "conversation_id", "project_id")
    @classmethod
    def _validate_uuid(cls, value: str) -> str:
        try:
            return str(UUID(str(value)))
        except ValueError as exc:
            raise ValueError("Identity fields must be valid UUIDs.") from exc

    @field_validator("created_at_utc", "completed_at_utc")
    @classmethod
    def _normalize_timestamp(cls, value: datetime | None) -> datetime | None:
        if value is None:
            return None
        if value.tzinfo is None:
            raise ValueError("Turn timestamps must be timezone-aware.")
        return value.astimezone(timezone.utc)

    @model_validator(mode="after")
    def _validate_state(self) -> "ConversationTurn":
        if self.status == ConversationTurnStatus.COMPLETED and self.completed_at_utc is None:
            raise ValueError("Completed turns require completed_at_utc.")
        if self.status == ConversationTurnStatus.FAILED and not self.failure_category:
            raise ValueError("Failed turns require failure_category.")
        if self.role == ConversationRole.USER and self.provider_provenance is not None:
            raise ValueError("User turns cannot have provider provenance.")
        text_parts = [item for item in self.content_parts if isinstance(item, ConversationTextPart)]
        evidence_parts = [item for item in self.content_parts if isinstance(item, ConversationEvidenceReferencePart)]
        explore_parts = [item for item in self.content_parts if isinstance(item, ConversationExploreReferencePart)]
        visual_artifact_parts = [item for item in self.content_parts if isinstance(item, ConversationVisualArtifactReferencePart)]
        investigation_parts = [item for item in self.content_parts if isinstance(item, ConversationInvestigationReferencePart)]
        if len(text_parts) != 1:
            raise ValueError("Phase 1B conversation turns require exactly one text part.")
        if self.role == ConversationRole.ASSISTANT and evidence_parts:
            raise ValueError("Phase 1B assistant turns cannot attach Evidence.")
        if len(evidence_parts) > MAX_CONVERSATION_IMAGE_REFERENCES:
            raise ValueError("Too many Evidence references.")
        if len({(item.container_id, item.resource_id) for item in evidence_parts}) != len(evidence_parts):
            raise ValueError("Duplicate Evidence references are not allowed.")
        if self.role == ConversationRole.USER and explore_parts:
            raise ValueError("Only assistant turns may reference an Explore interaction.")
        if len(explore_parts) > 1:
            raise ValueError("A turn may reference at most one Explore interaction.")
        if self.role == ConversationRole.USER and visual_artifact_parts:
            raise ValueError("Only assistant turns may reference a Visual Artifact.")
        if len(visual_artifact_parts) > 1:
            raise ValueError("A turn may reference at most one Visual Artifact.")
        if self.role == ConversationRole.USER and investigation_parts:
            raise ValueError("Only assistant turns may reference an Investigation.")
        if len(investigation_parts) > 1:
            raise ValueError("A turn may reference at most one Investigation.")
        return self


class ProjectConversation(BaseModel):
    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    schema_version: str = PROJECT_CONVERSATION_SCHEMA_VERSION
    conversation_id: str
    project_id: str
    created_at_utc: datetime
    updated_at_utc: datetime
    turns: list[ConversationTurn] = Field(default_factory=list)

    @field_validator("conversation_id", "project_id")
    @classmethod
    def _validate_uuid(cls, value: str) -> str:
        try:
            return str(UUID(str(value)))
        except ValueError as exc:
            raise ValueError("Identity fields must be valid UUIDs.") from exc

    @model_validator(mode="after")
    def _validate_turns(self) -> "ProjectConversation":
        expected = list(range(1, len(self.turns) + 1))
        actual = [item.sequence_number for item in self.turns]
        if actual != expected:
            raise ValueError("Conversation turns must have contiguous deterministic ordering.")
        if any(item.project_id != self.project_id or item.conversation_id != self.conversation_id for item in self.turns):
            raise ValueError("Conversation turn ownership mismatch.")
        if len({item.turn_id for item in self.turns}) != len(self.turns):
            raise ValueError("Conversation turn IDs must be unique.")
        return self


class ConversationSendRequest(BaseModel):
    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    text: str = Field(min_length=1, max_length=4000)
    idempotency_key: str = Field(min_length=1, max_length=128)
    evidence_refs: list[ConversationEvidenceReferencePart] = Field(
        default_factory=list, max_length=MAX_CONVERSATION_IMAGE_REFERENCES)


class ConversationReadResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    conversation_id: str
    project_id: str
    turns: list[ConversationTurn]


class ConversationSendResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    conversation_id: str
    project_id: str
    turns: list[ConversationTurn] = Field(min_length=2, max_length=2)
    reconstructed: bool = False
